### ISSUE TITLE
Crash in 0.95.9 when producing Harriers with payload upgrade

### ISSUE THREAD

**Issue by 0xf0cd** [patrickwieth/YMCA#1]
```
OpenRA engine version 0a06cf1789c66d8f5cf7566199187181aef0dbec
OpenRA Language: en
You Must Contruct Additional... mod version $v0.95.9
on map dbfaddb05e6ef43ddb4ab73fde95c0070bd43610 (Three on Two Remixed by DoubleJ).
Date: 2024-02-03 18:45:48Z
Operating System: Linux (Unix 6.7.1.1)
Runtime Version: .NET CLR 6.0.26
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.InvalidOperationException`: Model `harr.payload` does not have any sequences defined.
   at OpenRA.Mods.Cnc.Graphics.VoxelModelCache.GetModelSequence(String model, String sequence) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Mods.Cnc/Graphics/VoxelModelSequenceLoader.cs:line 104
   at OpenRA.Mods.Common.Traits.Render.WithVoxelBody..ctor(Actor self, WithVoxelBodyInfo info) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Mods.Common/Traits/Render/WithVoxelBody.cs:line 53
   at OpenRA.Mods.Common.Traits.Render.WithVoxelBodyInfo.Create(ActorInitializer init) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Mods.Common/Traits/Render/WithVoxelBody.cs:line 29
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/Actor.cs:line 161
   at OpenRA.Mods.Common.Traits.Production.<>c__DisplayClass7_0.<DoProduction>b__0(World w) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Mods.Common/Traits/Production.cs:line 139
   at OpenRA.World.Tick() in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/World.cs:line 448
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.LogicTick() in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Launcher/Program.cs:line 32
```

**Comment by patrickwieth** [comment]
Thank you for the bug report!

fixed by https://github.com/patrickwieth/YMCA/commit/3ecafa4a192ad0cdf724ab5604ff9acfbd99a402

The fix will be in the next release.
