### ISSUE TITLE
Crash in 0.95.9 when activating Firestorm Missile System

### ISSUE THREAD

**Issue by 0xf0cd** [patrickwieth/YMCA#2]
Crashes when using Firestorm Missile System power, available to GDI upgrade center.

```
OpenRA engine version 0a06cf1789c66d8f5cf7566199187181aef0dbec
OpenRA Language: en
You Must Contruct Additional... mod version $v0.95.9
on map 44cc6ba0f5ce4f9b205005c11f6ea1e6bccdc55d (All that Glitters - Barren by Westwood Studios).
Date: 2024-02-03 19:10:48Z
Operating System: Linux (Unix 6.7.1.1)
Runtime Version: .NET CLR 6.0.26
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.IO.FileNotFoundException`: File not found: rmissile.shp
   at OpenRA.Mods.Common.Graphics.FileNotFoundSequence.OpenRA.Graphics.ISpriteSequence.get_Tick() in /home/runner/work/YMCA/YMCA/engine/OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs:line 112
   at OpenRA.Graphics.Animation.PlaySequence(String sequenceName) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/Graphics/Animation.cs:line 126
   at OpenRA.Graphics.Animation.PlayRepeating(String sequenceName) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/Graphics/Animation.cs:line 141
   at OpenRA.Mods.Common.Projectiles.Bullet..ctor(BulletInfo info, ProjectileArgs args) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Mods.Common/Projectiles/Bullet.cs:line 159
   at OpenRA.Mods.Common.Projectiles.BulletInfo.Create(ProjectileArgs args) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Mods.Common/Projectiles/Bullet.cs:line 134
   at OpenRA.Mods.Common.Traits.Armament.<>c__DisplayClass34_0.<FireBarrel>b__2(Int32 burst) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Mods.Common/Traits/Armament.cs:line 329
   at OpenRA.Mods.Common.Traits.Armament.FireBarrel(Actor self, IFacing facing, Target& target, Barrel barrel) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Mods.Common/Traits/Armament.cs:line 325
   at OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target& target) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Mods.Common/Traits/Armament.cs:line 258
   at OpenRA.Mods.Common.Traits.AttackBase.DoAttack(Actor self, Target& target) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Mods.Common/Traits/Attack/AttackBase.cs:line 169
   at OpenRA.Mods.Common.Traits.AttackFollow.Tick(Actor self) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Mods.Common/Traits/Attack/AttackFollow.cs:line 155
   at OpenRA.TraitDictionary.TraitContainer`1.ApplyToAllTimed(Action`2 action, String text) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/TraitDictionary.cs:line 313
   at OpenRA.World.Tick() in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/World.cs:line 443
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.LogicTick() in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/YMCA/YMCA/engine/OpenRA.Launcher/Program.cs:line 32
```

**Comment by patrickwieth** [comment]
Thank you for the bug report!

fixed by [#844245c](https://github.com/patrickwieth/YMCA/commit/844245c9fe46f111f630d58d1166fe2195a01851)

The fix will be in the next release.
